# Generated by Django 4.1.5 on 2023-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatProfile',
            fields=[
                ('uid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, max_length=25, null=True)),
                ('l_name', models.CharField(blank=True, max_length=25, null=True)),
                ('dob', models.DateField()),
                ('parent_name', models.CharField(blank=True, max_length=55, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('referredby', models.CharField(blank=True, db_column='referredBy', max_length=3, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'pat_profile',
                'managed': False,
            },
        ),
    ]
