# Generated by Django 4.1.5 on 2023-01-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patprofile',
            options={},
        ),
    ]
