# Generated by Django 4.1.5 on 2023-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_alter_patprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
