# Generated by Django 4.1.5 on 2023-01-11 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0003_alter_patprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patprofile',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='patprofile',
            name='referredby',
        ),
        migrations.AddField(
            model_name='patprofile',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patprofile',
            name='referredBy',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
