# Generated by Django 4.0.4 on 2023-01-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0005_opdrecord_rename_createdat_patprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patprofile',
            name='uid',
            field=models.AutoField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
