# Generated by Django 4.0.4 on 2023-01-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0006_alter_patprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patprofile',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
