# Generated by Django 4.1.5 on 2023-01-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0007_alter_patprofile_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opdrecord',
            old_name='uid',
            new_name='id',
        ),
    ]
