# Generated by Django 4.1.5 on 2023-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0008_rename_uid_opdrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patprofile',
            name='uid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
