# Generated by Django 4.1.5 on 2023-01-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0009_alter_patprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdrecord',
            name='ref',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='apex.patprofile'),
            preserve_default=False,
        ),
    ]
