# Generated by Django 4.1.5 on 2023-01-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0010_alter_opdrecord_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdrecord',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.patprofile'),
        ),
    ]
