# Generated by Django 4.1.5 on 2023-01-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0011_alter_opdrecord_ref'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opdrecord',
            unique_together={('ref', 'id')},
        ),
    ]
