# Generated by Django 4.1.5 on 2023-01-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0012_alter_opdrecord_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opdrecord',
            table=None,
        ),
    ]
