# Generated by Django 4.1.5 on 2023-01-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0013_alter_opdrecord_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opdrecord',
            table='opd_record',
        ),
    ]
