# Generated by Django 4.1.5 on 2023-01-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0014_alter_opdrecord_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opdrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='opdrecord',
            name='ref_id',
            field=models.ForeignKey(db_column='ref', default=0, on_delete=django.db.models.deletion.CASCADE, to='apex.patprofile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='opdrecord',
            unique_together={('ref_id', 'id')},
        ),
        migrations.RemoveField(
            model_name='opdrecord',
            name='ref',
        ),
    ]
