# Generated by Django 4.1.5 on 2023-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0015_alter_opdrecord_unique_together_opdrecord_ref_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patprofile',
            old_name='uid',
            new_name='id',
        ),
    ]
